이슈 수정 API 구현
ghojeong/issue-tracker pull request #121
Opened 2021-07-04 10:49 UTC by sanhee

- Writer 구분을 위해 name 필드를 User의 id로 변경
- 마일스톤도 동시 업데이트
- IssueLabel, Assignee 테이블 업데이트는 추후

2021-07-04 10:52 UTC, sanhee commented
이전 pr이 아직 머지가 안돼서 중복되는 변경사항이 존재합니다..😂

2021-07-04 17:29 UTC, sanhee commented
@ghojeong  

질문이 있습니다.. 아래와 같은 컨트롤러에서 JSON 리퀘스트를 `AssigneeRequest` 를 파라미터로 받으려고 합니다.
하지만, 역직렬화 과정에서 문제가 생겨 Assignee를 생성하는 API를 구현하지 못했습니다...
엉망인 코드라서 따로 커밋은 하지 않았고, 도움을 요청하기 위해 코멘트를 남깁니다.🥕🥕🥕

```json

// JSON 리퀘스트
{
    "assigneeIds": ["neo","san"]
}
```


```java
public class AssigneeRequest {

    private final List<String> assigneeIds;
    
    public AssigneeRequest(List<String> assigneeIds) {
        this.assigneeIds = assigneeIds;
    }

    public List<String> getAssigneeIds() {
        return assigneeIds;
    }
}
```

```java
public void addAssignees(@PathVariable Long issueId, @RequestBody AssigneeRequest assigneeRequest, HttpServletRequest request) {
...
}
```


```text
2021-07-05 02:22:06.099 ERROR 16784 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class com.issuetracker.dto.request.AssigneeRequest]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.issuetracker.dto.request.AssigneeRequest` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (PushbackInputStream); line: 2, column: 5]] with root cause

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.issuetracker.dto.request.AssigneeRequest` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (PushbackInputStream); line: 2, column: 5]
```

2021-07-04 21:56 UTC, ghojeong requested changes
궁금한것 질문으로 남깁니다.

2021-07-04 21:56 UTC, ghojeong commented on backend/server/src/main/java/com/issuetracker/repository/sql/IssueQueries.kt
> +UPDATE issue SET title = :title, content = :content, writerId = :writerId, milestoneId = :milestoneId
writerId 를 업데이트 해야하는 경우가 있나요?
가령 제가 쓴 댓글을 노을이 수정하면, 제가 쓴 댓글의 writer 가 저에서 노을로 변경되는 건가요?

2021-07-04 21:56 UTC, ghojeong commented on backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java
> +        issueService.updateIssue(loginUser, issue, issueId);
```suggestion
    public void updateIssue(@RequestBody IssueRequest issue, @PathVariable Long issueId) {
        issueService.updateIssue(issue, issueId);
```

issue 를 업데이트 하는데 유저 정보가 왜 필요한지 여쭈어봅니다.

2021-07-04 22:14 UTC, ghojeong requested changes

2021-07-04 22:14 UTC, ghojeong commented on backend/server/src/main/java/com/issuetracker/dto/request/AssigneesRequest.java
> +    }
**Cannot construct instance** 라는 에러메시지가 Jackson 에서 뜰 때는,
인자가 아무것도 없는 생성자 (`protected AssigneesRequest() {}`)를 만들면 됩니다.
삽질이 부족하시거나, 삽질에 대한 정리 및 학습이 부족하시군요 노을 ㅋㅋㅋㅋ

이게 다~ 야근을 해서 그렇습니다.
밤새워서 작업을 하면, 경험한 내용들이 시간이 지나면 머릿속에 남지 않고 사라집니다.
마치 벼락치기하면, 시험을 치루고 나서 머릿속에 별로 남지 않는 것과 비슷합니다.

2021-07-05 02:38 UTC, sanhee commented on backend/server/src/main/java/com/issuetracker/repository/sql/IssueQueries.kt
> +UPDATE issue SET title = :title, content = :content, writerId = :writerId, milestoneId = :milestoneId
앗 아닙니다.. 전체 필드를 적다 보니 생각이 없이 적었습니다.
이 부분 수정하겠습니다!

2021-07-05 02:39 UTC, sanhee commented on backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java
> +        issueService.updateIssue(loginUser, issue, issueId);
위에서 답변 드렸습니다!..

2021-07-05 02:45 UTC, sanhee commented on backend/server/src/main/java/com/issuetracker/dto/request/AssigneesRequest.java
> +    }
새벽 작업은 정말 조심해야겠네요 ㅎㅎ

언급 해주신 기본 생성자의 경우 사실 시도를 해봤었는데, NRE 에러가 발생해서 수정 전 코드를 질문 드렸던 것인데

다음부터는 좀 더 짜임새 있는 질문을 해보도록 하겠습니다..!

----

오전에 파이로와 같이 디버깅을 해본 결과

mac 환경에서는 역직렬화가 정상적으로 되지만, 윈도우에서는 되지 않는 점을 확인했습니다.

아직 원인은 정확하게 파악하지 못했고,  Jackson 라이브러리의 @JsonProperty를 사용하여 해결하였습니다.

```java
public class AssigneesRequest {

    @JsonProperty("assigneeIds")
    private List<String> assigneeIds;

    protected AssigneesRequest() {
    }

    public AssigneesRequest(List<String> assigneeIds) {
        this.assigneeIds = assigneeIds;
    }

    public List<String> getAssigneeIds() {
        return assigneeIds;
    }
}

```

2021-07-05 02:58 UTC, sanhee commented on backend/server/src/main/java/com/issuetracker/repository/sql/IssueQueries.kt
> +UPDATE issue SET title = :title, content = :content, writerId = :writerId, milestoneId = :milestoneId
ee97bbc
수정완료했습니다.

2021-07-05 02:58 UTC, sanhee commented on backend/server/src/main/java/com/issuetracker/controller/web/WebIssueController.java
> +        issueService.updateIssue(loginUser, issue, issueId);
ee97bbc 수정했습니다!

2021-07-05 03:13 UTC, sanhee commented
@ghojeong 

요구사항 구현 완료했습니다~!✨

2021-07-05 03:16 UTC, ghojeong commented
오우! 수고하셨습니다!
점심 먹고 확인해보겠습니다!

2021-07-05 03:44 UTC, ghojeong approved these changes
고생하셨습니다. 👍 
배포을 위해 머지하겠습니다.

2021-07-05 03:44 UTC, ghojeong commented on backend/server/src/main/java/com/issuetracker/repository/IssueRepository.java
>          jdbc.update(INSERT_ASSIGNEE, parameter);
어려우시면 안하셔도 됩니다.
어차피 JPA 를 사용하게 되면 전부 지워야할 코드 입니다 ㅋㅋㅋ

2021-07-05 03:44 UTC, merged